/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package perpustakaan;

import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author User
 */
public class anggota extends javax.swing.JFrame {
    
    Connection con;
    Statement stat;
    ResultSet res;
    PreparedStatement st;
    String tLahir;
    
    private void loaddata(){
       DefaultTableModel t = new DefaultTableModel();
        t.addColumn("NISN");
        t.addColumn("Nama");
        t.addColumn("TTL");
        t.addColumn("Jenis Kelamin");
        t.addColumn("Alamat");
        t.addColumn("Kelas");
        tata.setModel(t);
        try{
            res=stat.executeQuery("Select * from anggota");
            
            while (res.next()){
                t.addRow(new Object[]
                {
                    res.getString("nim"),
                    res.getString("nama"),
                    res.getString("ttl"),
                    res.getString("jenis_kelamin"),
                    res.getString("alamat"),
                    res.getString("kelas"),
                });
            }
        } catch (Exception e){
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }

    /**
     * Creates new form anggota
     */
    public anggota() {
        initComponents();
        setLocationRelativeTo(null);
        koneksi();
        loaddata();
    }
    
    private void koneksi(){
        try{
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/database_perpustakaan", "root", "");
            stat = con.createStatement();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nisn = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        jk = new javax.swing.JTextField();
        alamat = new javax.swing.JTextField();
        kelas = new javax.swing.JTextField();
        ttl = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        save = new javax.swing.JButton();
        refresh = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tata = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Perpustakaan SMKN 2 Padang");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Data Anggota");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 11, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 102));
        jLabel2.setText("NISN");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 0, 102));
        jLabel3.setText("Nama");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 0, 102));
        jLabel4.setText("TTL");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 0, 102));
        jLabel5.setText("Jenis Kelamin");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 0, 102));
        jLabel6.setText("Alamat");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 0, 102));
        jLabel7.setText("Kelas");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, -1, -1));

        nisn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(nisn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 219, -1));

        nama.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 219, -1));

        jk.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(jk, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 219, -1));

        alamat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 219, -1));

        kelas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(kelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 219, -1));

        ttl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ttl.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                ttlPropertyChange(evt);
            }
        });
        getContentPane().add(ttl, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 220, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, -1, -1));

        edit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        edit.setText("Edit");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        getContentPane().add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 150, 75, -1));

        save.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, 75, -1));

        refresh.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        refresh.setText("Refresh");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });
        getContentPane().add(refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 100, -1, -1));

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton5.setText("Delete");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 150, 79, -1));

        exit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 190, 79, -1));

        tata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tataMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tata);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 383, 741, 145));

        jLabel8.setIcon(new javax.swing.ImageIcon("D:\\SMKN 2 Padang\\XI-RPL\\Pemrograman Berorientasi Objek\\Aplikasi & Program\\Aplikasi Perpustakaan\\Asset\\bgAnggota.png")); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 570));

        setSize(new java.awt.Dimension(804, 612));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String x = JOptionPane.showInputDialog(null, "Masukkan NISN!!");
        try{
            String cari = "select * from anggota where NIM='"+x+"'";
            
            Statement stat = con.createStatement();
            res = stat.executeQuery(cari);
            
            if(res.next()){
                System.out.println(res.getString(1));
                JOptionPane.showMessageDialog(null, "Data ditemukan");
                nisn.setText(res.getString(1));
                nama.setText(res.getString(2));
                
                try{
                    java.util.Date date = new SimpleDateFormat("yyyy-MM-dd").parse((String)res.getString(3));
                    ttl.setDate(date);
                } catch (ParseException ex) { 
                    Logger.getLogger(transaksi.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                jk.setText(res.getString(4));
                alamat.setText(res.getString(5));
                kelas.setText(res.getString(6));
            } else {
                JOptionPane.showMessageDialog(null, "Data Tidak ditemukan");
            }
        } catch (Exception e){
            System.out.print(e);
            JOptionPane.showMessageDialog(null, "Koneksi Gagal");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
        int coba = JOptionPane.showConfirmDialog(null, "Yakin untuk mengubah data ini?","Confirmation", JOptionPane.YES_NO_OPTION);
        try{
            String sql = "update anggota set NIM=?, Nama=?, TTL=?,Jenis_Kelamin=?,Alamat=?,Kelas=? where " + "NIM='"+nisn.getText()+"'";
            st=con.prepareStatement(sql);
            
            if(coba==0){
                try{
                    st.setString(1, nisn.getText());
                    st.setString(2, nama.getText());
                    st.setString(3, tLahir);
                    st.setString(4, jk.getText());
                    st.setString(5, alamat.getText());
                    st.setString(6, kelas.getText());
                    st.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Update data sukses");
                    loaddata();
                } catch(Exception e){
                    JOptionPane.showMessageDialog(null, "Update data Gagal" + e);
                }
            }
        } catch(Exception e){
            
        }
    }//GEN-LAST:event_editActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        try{
            String sqlnya = ("insert into anggota values ('"
            +nisn.getText()+"','"
            +nama.getText()+"','"
            +tLahir+"','"
            +jk.getText()+"','"
            +alamat.getText()+"','"
            +kelas.getText()+"')");
            
            stat.executeUpdate(sqlnya);
            JOptionPane.showMessageDialog(null, "Data Tersimpan");
            loaddata();
                    
        } catch (Exception e){
            System.out.print(e);
            JOptionPane.showMessageDialog(null, "Koneksi Gagal");
        }
    }//GEN-LAST:event_saveActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
         if(JOptionPane.showConfirmDialog(null, "Apakah anda ingin keluar?","Yakin", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
           this.dispose();
           new loginadmin().show();
        }
    }//GEN-LAST:event_exitActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        // TODO add your handling code here:
        nisn.setText(null);
        nama.setText(null);
        ttl.setDate(null);
        jk.setText(null);
        alamat.setText(null);
        kelas.setText(null);
    }//GEN-LAST:event_refreshActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String x = nisn.getText();
        
        try{
            String sql="delete from anggota where nim='"+x+"'";
            stat.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Data telah dihapus");
            loaddata();
            nisn.setText(null);
            nama.setText(null);
            ttl.setDate(null);
            jk.setText(null);
            alamat.setText(null);
            kelas.setText(null);
            
        } catch (Exception e){
            System.out.println(e);
            JOptionPane.showMessageDialog(null, "Koneksi Gagal");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void tataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tataMouseClicked
        // TODO add your handling code here:
        int i = tata.getSelectedRow();
        TableModel model = tata.getModel();
        
        if(i == -1){
            return;
        }
        
        String code = (String)tata.getValueAt(i,0);
        String code1 = (String)tata.getValueAt(i,1);
        String code2 = (String)tata.getValueAt(i,2);
        String code3 = (String)tata.getValueAt(i,3);
        String code4 = (String)tata.getValueAt(i,4);
        String code5 = (String)tata.getValueAt(i,5);
        
        nisn.setText(code);
        nama.setText(code1);
        
        try{
            int srow = tata.getSelectedRow();
            java.util.Date date = new SimpleDateFormat("yyyy-MM-dd").parse((String)model.getValueAt(i,2));
            ttl.setDate(date);
        } catch (ParseException ex) { 
            Logger.getLogger(transaksi.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        jk.setText(code3);
        alamat.setText(code4);
        kelas.setText(code5);
    }//GEN-LAST:event_tataMouseClicked

    private void ttlPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_ttlPropertyChange
        // TODO add your handling code here:
        if(ttl.getDate() != null){
            SimpleDateFormat tgl = new SimpleDateFormat("yyy-MM-dd");
            tLahir = tgl.format(ttl.getDate());
        }
    }//GEN-LAST:event_ttlPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(anggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(anggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(anggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(anggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new anggota().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamat;
    private javax.swing.JButton edit;
    private javax.swing.JButton exit;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jk;
    private javax.swing.JTextField kelas;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField nisn;
    private javax.swing.JButton refresh;
    private javax.swing.JButton save;
    private javax.swing.JTable tata;
    private com.toedter.calendar.JDateChooser ttl;
    // End of variables declaration//GEN-END:variables
}
