/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package perpustakaan;

import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author User
 */
public class transaksi extends javax.swing.JFrame {
    
    Connection conn;
    Statement stat;
    ResultSet res;
    Connection con;
    PreparedStatement st;
    String tPinjam, tKembali;
    /**
     * Creates new form transaksi
     */
    public transaksi() {
        initComponents();
        koneksi();
        loaddata();
        loaddata1();
    }
    
    private void loaddata(){
        DefaultTableModel t = new DefaultTableModel();
        t.addColumn("Kode Buku");
        t.addColumn("Nama Buku");
        t.addColumn("Nama Pengarang");
        t.addColumn("Penerbit");
        t.addColumn("Tahun Terbit");
        tabuk.setModel(t);
        try{
            res=stat.executeQuery("Select * from data_buku");

            while (res.next()){
                t.addRow(new Object[]
                {
                    res.getString("kode_buku"),
                    res.getString("nama_buku"),
                    res.getString("nama_pengarang"),
                    res.getString("penerbit"),
                    res.getString("tahun_terbit")
                });
            }
        } catch (Exception e){
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }
    
    private void koneksi(){
        try{
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://127.0.0.1/database_perpustakaan","root","");
            stat = conn.createStatement();
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private void loaddata1(){
       DefaultTableModel t = new DefaultTableModel();
        t.addColumn("NISN");
        t.addColumn("Nama");
        t.addColumn("Kode Buku");
        t.addColumn("Nama Buku");
        t.addColumn("Tanggal Peminjaman");
        t.addColumn("Tanggal Pengembalian");
        peminjam.setModel(t);
        try{
            res=stat.executeQuery("Select * from peminjam");
            
            while (res.next()){
                t.addRow(new Object[]
                {
                    res.getString("nim"),
                    res.getString("nama"),
                    res.getString("kode_buku"),
                    res.getString("nama_buku"),
                    res.getString("tanggal_peminjaman"),
                    res.getString("tanggal_pengembalian"),
                });
            }
        } catch (Exception e){
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nisn = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        Kode_Buku = new javax.swing.JLabel();
        kodebuku = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        namabuku = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        peminjam = new javax.swing.JTable();
        save = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        search = new javax.swing.JButton();
        tampil = new javax.swing.JButton();
        tglPinjam = new com.toedter.calendar.JDateChooser();
        tglKembali = new com.toedter.calendar.JDateChooser();
        refresh = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabuk = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Perpustakaan SMKN 2 Padang");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Peminjaman Buku");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("NISN");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 108, -1, -1));

        nisn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nisn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nisnKeyReleased(evt);
            }
        });
        getContentPane().add(nisn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 219, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Nama");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 151, -1, -1));

        nama.setEditable(false);
        nama.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 219, -1));

        Kode_Buku.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Kode_Buku.setText("Kode Buku");
        getContentPane().add(Kode_Buku, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        kodebuku.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        kodebuku.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                kodebukuKeyReleased(evt);
            }
        });
        getContentPane().add(kodebuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 219, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Nama Buku");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        namabuku.setEditable(false);
        namabuku.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(namabuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 219, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Tanggal Pinjam");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Tanggal Kembali");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        peminjam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        peminjam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                peminjamMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(peminjam);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 408, 741, 221));

        save.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(528, 201, 75, -1));

        exit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(639, 201, 79, -1));

        delete.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(639, 147, 79, -1));

        edit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        edit.setText("Edit");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        getContentPane().add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(528, 147, 75, -1));

        search.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        getContentPane().add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(528, 104, -1, -1));

        tampil.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tampil.setText("Tampilkan Semua Data");
        tampil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tampilActionPerformed(evt);
            }
        });
        getContentPane().add(tampil, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 250, 190, -1));

        tglPinjam.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tglPinjam.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tglPinjamPropertyChange(evt);
            }
        });
        getContentPane().add(tglPinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 220, -1));

        tglKembali.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tglKembali.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tglKembaliPropertyChange(evt);
            }
        });
        getContentPane().add(tglKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 220, -1));

        refresh.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        refresh.setText("Refresh");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });
        getContentPane().add(refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(639, 104, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Tabel Data Peminjam");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 373, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Tabel Data Buku");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 100, -1, -1));

        tabuk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabuk);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 130, 490, 500));

        jLabel4.setIcon(new javax.swing.ImageIcon("D:\\SMKN 2 Padang\\XI-RPL\\Pemrograman Berorientasi Objek\\Aplikasi & Program\\Aplikasi Perpustakaan\\Asset\\bgTransaksi.png")); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 650));

        setSize(new java.awt.Dimension(1316, 685));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void peminjamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_peminjamMouseClicked
        // TODO add your handling code here:
       
        int i = peminjam.getSelectedRow();
        TableModel model = peminjam.getModel();
        
        if(i == -1){
            return;
        }

        String code = (String)peminjam.getValueAt(i,0);
        String code1 = (String)peminjam.getValueAt(i,1);
        String code2 = (String)peminjam.getValueAt(i,2);
        String code3 = (String)peminjam.getValueAt(i,3);
        String code4 = (String)peminjam.getValueAt(i,4);
        String code5 = (String)peminjam.getValueAt(i,5);
        
        try{
            int srow = peminjam.getSelectedRow();
            java.util.Date date = new SimpleDateFormat("yyyy-MM-dd").parse((String)model.getValueAt(srow, 4));
            tglPinjam.setDate(date);
        } catch (ParseException ex) { 
            Logger.getLogger(transaksi.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try{
            int srow = peminjam.getSelectedRow();
            java.util.Date date = new SimpleDateFormat("yyyy-MM-dd").parse((String)model.getValueAt(srow, 5));
            tglKembali.setDate(date);
        } catch (ParseException ex) { 
            Logger.getLogger(transaksi.class.getName()).log(Level.SEVERE, null, ex);
        }

        nisn.setText(code);
        nama.setText(code1);
        kodebuku.setText(code2);
        namabuku.setText(code3);
    }//GEN-LAST:event_peminjamMouseClicked

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        String x = nisn.getText();
        String y = kodebuku.getText();
        boolean cekData = false;
        boolean sttBuku = false;
        
        try{
            String sql1 = "Select * from peminjam where NIM like '%" + 
                    x+"%'";
            Statement stat = conn.createStatement();
            res = stat.executeQuery(sql1);
            
            if(res.next()){
               cekData = true; 
            }
             
        } catch (Exception e){
            
        }
        
        
        try{
            String sql1 = "Select * from data_buku where kode_buku like '%" + 
                    y+"%'";
            Statement stat = conn.createStatement();
            res = stat.executeQuery(sql1);
            
            if(res.next()){
               sttBuku = true; 
            }
             
        } catch (Exception e){
            
        }
        
        if(cekData = true){
            if(sttBuku = true){
                try{
                    stat.executeUpdate("insert into peminjam values ("
                        + "'" +nisn.getText()+"',"
                        + "'" +nama.getText()+"',"
                        + "'" +kodebuku.getText()+"',"
                        + "'" +namabuku.getText()+"',"
                        + "'" +tPinjam+"',"
                        + "'" +tKembali+"')"
                    );

                    loaddata1();
                    JOptionPane.showMessageDialog(null, "Berhasil Menyimpan Data");
                    loaddata();

                } catch (Exception e){
                    JOptionPane.showMessageDialog(null, "Perintah Salah: " + e);
                }
                
            } else {
                JOptionPane.showMessageDialog(null, "Buku yang anda pilih tidak terdaftar!!");
            }
              
        } else {
            JOptionPane.showMessageDialog(null, "Anda Belum Terdaftar Menjadi Anggota Perpustakaan!!");
        }
        
        
    }//GEN-LAST:event_saveActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(null, "Apakah anda ingin keluar?","Yakin", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            this.dispose();
            new menuutama().show();
        }
    }//GEN-LAST:event_exitActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        String y = nisn.getText();
        String x = kodebuku.getText();

        try{
            String sql="delete from peminjam where Kode_Buku='"+x+"' and nim='"+y+"'";
            stat.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Data telah dihapus");
            loaddata1();
            nisn.setText(null);
            nama.setText(null);
            kodebuku.setText(null);
            namabuku.setText(null);
            tglPinjam.setDate(null);
            tglKembali.setDate(null);

        } catch (Exception e){
            System.out.println(e);
            JOptionPane.showMessageDialog(null, "Koneksi Gagal");
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
        int coba = JOptionPane.showConfirmDialog(null, "Yakin untuk mengubah data ini?","Confirmation", JOptionPane.YES_NO_OPTION);
        try{
            String sql = "update peminjam set NIM=?, Nama=?, Kode_Buku=?,Nama_Buku=?,Tanggal_Peminjaman=?,Tanggal_Pengembalian=? where " +
                    "nim='"+nisn.getText()+"' and kode_buku='"+kodebuku.getText()+"'";
            st=conn.prepareStatement(sql);

            if(coba==0){
                try{
                    st.setString(1, nisn.getText());
                    st.setString(2, nama.getText());
                    st.setString(3, kodebuku.getText());
                    st.setString(4, namabuku.getText());
                    st.setString(5, tPinjam);
                    st.setString(6, tKembali);
                    st.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Update data sukses");
                    loaddata1();
                } catch(Exception e){
                    JOptionPane.showMessageDialog(null, "Update data Gagal" + e);
                }
            }
        } catch(Exception e){

        }
    }//GEN-LAST:event_editActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
//        String x = JOptionPane.showInputDialog(null, "Masukkan NISN!!");
//        try{
//            String cari = "select * from peminjam where nim='"+x+"'";
//            res = stat.executeQuery(cari);
//
//            if(res.next()){
//                System.out.println(res.getString(1));
//                JOptionPane.showMessageDialog(null, "Data ditemukan");
//                nisn.setText(res.getString("nim"));
//                nama.setText(res.getString("nama"));
//                kodebuku.setText(res.getString("kode_buku"));
//                namabuku.setText(res.getString("nama_buku"));
//                tglp.setText(res.getString("tanggal_peminjaman"));
//                tglk.setText(res.getString("tanggal_pengembalian"));
//            } else {
//                JOptionPane.showMessageDialog(null, "Data Tidak ditemukan");
//            }
//        } catch (Exception e){
//            System.out.print(e);
//            JOptionPane.showMessageDialog(null, "Koneksi Gagal");
//        }

        String x = JOptionPane.showInputDialog(null, "Cari Berdasarkan NISN / Kode Buku / Tanggal Peminjaman!!");
        
        DefaultTableModel tabel = new DefaultTableModel();
        tabel.addColumn("NISN");
        tabel.addColumn("Nama");
        tabel.addColumn("Kode Buku");
        tabel.addColumn("Nama Buku");
        tabel.addColumn("Tanggal Peminjaman");
        tabel.addColumn("Tanggal Pengembalian");
        
        
        
        try{
            String sql1 = "Select * from peminjam where NIM like '%" + 
                    x+"%' or Kode_Buku like '%"+
                    x+"%' or Tanggal_Peminjaman like '%"+
                    x+"%'";
            Statement stat = conn.createStatement();
            ResultSet res = stat.executeQuery(sql1);
            
            while(res.next()){
                tabel.addRow(new Object[]
                {
                    res.getString("nim"), 
                    res.getString("Nama"), 
                    res.getString("kode_buku"),
                    res.getString("Nama_buku"),
                    res.getString("tanggal_peminjaman"),
                    res.getString("tanggal_pengembalian")
                });
                peminjam.setModel(tabel);
            }
            
        } catch (Exception e){
            
        }
    }//GEN-LAST:event_searchActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        // TODO add your handling code here:
        nisn.setText(null);
        nama.setText(null);
        kodebuku.setText(null);
        namabuku.setText(null);
        tglPinjam.setDate(null);
        tglKembali.setDate(null);
    }//GEN-LAST:event_refreshActionPerformed

    private void tampilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tampilActionPerformed
        // TODO add your handling code here:
        loaddata1();
    }//GEN-LAST:event_tampilActionPerformed

    private void nisnKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nisnKeyReleased
        // TODO add your handling code here:
        String x = nisn.getText();
        
        try{
            String sql2 =  "Select * from Anggota where NIM like '%" + 
                    x+"%'";
            Statement stat = conn.createStatement();
            res = stat.executeQuery(sql2);
            
            if(res.next()){
                nama.setText(res.getString(2));
            } else {
                nama.setText("");
            }
            
        } catch (Exception e){
            
        }
    }//GEN-LAST:event_nisnKeyReleased

    private void kodebukuKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kodebukuKeyReleased
        // TODO add your handling code here:
        String x = kodebuku.getText();
        
        try{
            String sql2 =  "Select * from data_buku where kode_buku like '%" + 
                    x+"%'";
            Statement stat = conn.createStatement();
            res = stat.executeQuery(sql2);
            
            if(res.next()){
                namabuku.setText(res.getString(2));
            } else{
                namabuku.setText("");
            }
        } catch (Exception e){
            
        }
    }//GEN-LAST:event_kodebukuKeyReleased

    private void tglKembaliPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tglKembaliPropertyChange
        // TODO add your handling code here:
        if(tglKembali.getDate() != null){
            SimpleDateFormat tgl = new SimpleDateFormat("yyy-MM-dd");
            tKembali = tgl.format(tglKembali.getDate());
        }
    }//GEN-LAST:event_tglKembaliPropertyChange

    private void tglPinjamPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tglPinjamPropertyChange
        // TODO add your handling code here:
        if(tglPinjam.getDate() != null){
            SimpleDateFormat tgl = new SimpleDateFormat("yyy-MM-dd");
            tPinjam = tgl.format(tglPinjam.getDate());
        }
    }//GEN-LAST:event_tglPinjamPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new transaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Kode_Buku;
    private javax.swing.JButton delete;
    private javax.swing.JButton edit;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField kodebuku;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField namabuku;
    private javax.swing.JTextField nisn;
    private javax.swing.JTable peminjam;
    private javax.swing.JButton refresh;
    private javax.swing.JButton save;
    private javax.swing.JButton search;
    private javax.swing.JTable tabuk;
    private javax.swing.JButton tampil;
    private com.toedter.calendar.JDateChooser tglKembali;
    private com.toedter.calendar.JDateChooser tglPinjam;
    // End of variables declaration//GEN-END:variables
}
